import { Daten } from './Daten';

export const daten: Daten[] = [
  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },  { id: "Beta", username: 'Dr. Nice', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Alpha", username: 'Bombasto', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Microsoft", username: 'Celeritas', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "Ralfhausen", username: 'Magneta', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rubberband", username: 'RubberMan', passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
  { id: "rastawista", username: 'Dynama',  passwort: "adsoif", email: "RistawistaAlasista@gmx.de" },
];